language: java
jdk: oraclejdk8

addons:
    sonarcloud:
        organization: "sweihmws2018-19"

script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
    - mvn package
